### PR TITLE
[WFLY-14281] - Integrate MP Fault Tolerance 3.0 into EAP

### PR DESCRIPTION
**Pull request by jasondlee**

### CODE REVIEW

**Comment by Ladicek** [comment]
FYI, SmallRye Fault Tolerance 5.0.0 has been released and the release announcement should be up soon.

**Comment by Ladicek** [comment]
Aaand it's there: https://smallrye.io/blog/fault-tolerance-5-0/ It's got links to documentation and a section on integration changes.

**Comment by jasondlee** [comment]
> Aaand it's there: https://smallrye.io/blog/fault-tolerance-5-0/ It's got links to documentation and a section on integration changes.

Awesome. Thanks!

**Comment by rhusar** [comment]
Replaced with https://github.com/wildfly/wildfly-proposals/pull/368 with the original changes here and couple of changes e.g. pointed out by QE.

**Pull request closed without merging**
