### PR TITLE
WFLY-10328 Agroal subsystem

### PR DESCRIPTION
**Pull request by barreiro**
EAP feature https://issues.jboss.org/browse/EAP7-983

### CODE REVIEW

**Comment by barreiro** [comment]
@dmlloyd yes it was. Security integration has been on the requirements from day one.

**Comment by simkam** [comment]
@istraka @fmarchioni I suppose this will need tests also in transaction test suites, can you review this too? 
@barreiro have you considered also pool-less setup for scenarios where other pool is used instead of driver? f.ex Oracle UCP

**Comment by barreiro** [comment]
@simkam yes, we had discussions around pool-less and is something we may add in the near future (probably as a third datasource type besides XA and non-XA)

**Comment by jamezp** [comment]
We should document whether or not something like the `*-ds.xml` will be supported this subsystem.

**Comment by jmesnil** [comment]
@jamezp by `*-ds.xml` you mean the IronJacamar's deployment files? If that's the case, I don't think the new subsystem would have to support it (as a comparison, the `messaging-activemq` subsystem does not support the `*-jms.xml` from the legacy `messaging` subsystem).

Besides, the new subsystem supports the standard Java EE7 datasource definition annotations and XML file as defined Java EE7 spec (chapter EE.5.18.3)

**Comment by johnathonlee** [comment]
@jmesnil `*-ds.xml` predated IronJacamar and is not an IJ deployment file.  For EAP it was considered an unmanaged connection: https://access.redhat.com/solutions/85163

**Comment by kabir** [comment]
@barreiro Can you please add in the new Community Documentation section I just mentioned on wildfly-dev?

**Comment by barreiro** [comment]
Added the Community Documentation section

**Comment by darranl** [comment]
Has there been any consideration to running this in a HostController process? Getting access to databases from the HostController process is still an issue for some.  I don't think this needs to be in the initial work but could be a good follow up.

**Comment by barreiro** [comment]
@darranl no, that use case hasn't taken into consideration.

**Comment by darranl** [comment]
@barreiro Ok, could be a good one to discuss under it's own RFE, let me know if you want to chat some time about when it would be used.

**Pull request merged**
