### PR TITLE
[WFLY-13003] Analysis document for SameSite cookie attribute changes

### PR DESCRIPTION
**Pull request by fl4via**
Jira: https://issues.redhat.com/browse/WFLY-13003
EAP7: https://issues.redhat.com/browse/EAP7-1422

### CODE REVIEW

**Comment by jmesnil** [comment]
looks good to me.

As I understand this does not impact any of the HTTP endpoints we have in WildFly management interface as we don't rely on cookies for them. @fl4via is that correct?

**Comment by fl4via** [comment]
@jmesnil  Yes, that's correct. It is just an added feature to make applications compliant with the new rules for cookie attribute `SameSite`. The users that wish to use this handler will do so via expression-filter, such as:
/subsystem=undertow/configuration=filter/expression-filter=addSameSiteLax:add(expression="path-prefix('/mypathprefix') -> samesite-cookie(Lax)")
And then apply the filter to the host via:
/subsystem=undertow/server=default-server/host=default-host/filter-ref=addSsameSiteLax:add
Or the user could use WEB-INF/undertow-handlers.conf as an alternative.

**Comment by fl4via** [comment]
@jamezp I added the information on the parameter that adds secure for none. If you could re-review it, it would be great!

**Comment by jamezp** [comment]
Looks good to me @fl4via

**Pull request merged**
