### PR TITLE
[WFCORE-3932]: Adding support for standalone to standalone model synchronization / model difference computation

### PR DESCRIPTION
**Pull request by ehsavoie**
Jira: https://issues.jboss.org/browse/WFCORE-3932
Current code status: https://github.com/ehsavoie/wildfly-core/tree/WFCORE-3932

### CODE REVIEW

**Comment by aloubyansky** [comment]
From Galleon and provisioning perspective and roadmap the described functionality is a highly critical one that we need, ASAP. Thanks.

**Comment by kabir** [comment]
@ehsavoie Can you please add in the new Community Documentation section I just mentioned on wildfly-dev?

**Comment by LittleJohnII** [comment]
@kabir can we get an EAP7 planning issue for this?
@ehsavoie I have a question about the requirements in the proposal. In hard requirements you write that this should target the complete model, including deployments. In non-requirements, there's written that files (including deployments) are not targeted. IIUC, this means that the result of the diff will contain the information about what was deployed, but not the actual deployment files?

**Comment by ehsavoie** [comment]
@LittleJohnII yes you are correct, Galleon provides already the filesystem changes so those files are already available. In a could environment I guess the deployment files would me mounted shared filesystem or whatever thus only the information about which files we are going to use is pertinent.

**Comment by aloubyansky** [comment]
Reabsed (had to fix the build) commit is https://github.com/aloubyansky/wildfly-core/commit/426251ab7c0e80ae135440085b86e7c16cbff095

**Pull request closed without merging**
