### PR TITLE
WFLY-9664 Add support for configuring scattered caches

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/EAP7-867
https://issues.jboss.org/browse/WFLY-9664

### CODE REVIEW

**Comment by rhusar** [comment]
I think we should vaguely mirror the WildFly repository directory structure, so here I suggest we use `clustering/infinispan/`. E.g. here https://github.com/wildfly/wildfly-proposals/pull/10 I am creating the jgroups dir `clustering/jgroups/`

**Comment by rhusar** [comment]
Also, since the process is open, I suggest we name documents by their upstream and publicly visible issues (not internal ones).

**Comment by kabir** [comment]
+1 - we have not been strict for this for WF12 due to the time pressure, but want to do this for things now coming for WF13

**Comment by mvinkler** [comment]
QE feedback: looks OK.

**Pull request merged**
