### PR TITLE
[WFCORE-4355] Add proposal for event-logging API.

### PR DESCRIPTION
**Pull request by jamezp**
https://issues.jboss.org/browse/WFCORE-4355

### CODE REVIEW

**Comment by jmesnil** [comment]
@jamezp I looked at https://github.com/wildfly/wildfly-core/pull/3700 and I was wondering if this belongs to wildfly-core codebase or should be a separate project (under the wildfly organization).

**Comment by darranl** [comment]
+1 for the comment from @jmesnil - if this lives within WildFly Core then components that come in to WildFly Core would not be able to depend on it.

On the other hand maybe that is correct and the subsystem responsible for a component should then be required to handle wiring the two together.  If this did not live within WildFly Core would it have any meaning on the outside?

**Comment by jamezp** [comment]
So far I'm not aware of anything outside of WildFly that would use this. The only component I can think of would be Elytron. We can move it to it's own project outside core, but I figured we could start in core and if needed we refactor it out later. I'm good with either option though.

**Comment by jamezp** [comment]
I'm merging this because the WildFly Core PR was merged.

**Pull request merged**
