### PR TITLE
WFLY-14559: Updated WFLY-14559_Add_six_new_RESTEasy_context_parameter…

### PR DESCRIPTION
**Pull request by ronsigal**
…s.adoc

This is a copy of https://github.com/wildfly/wildfly-proposals/pull/560, which, somehow, I closed. I've copied all of the relevant comments and responded to them.

### CODE REVIEW

**Comment by ronsigal** [comment]
* {issue-base-url}/RESTEASY-2280[RESTEASY-2280]
* {issue-base-url}/RESTEASY-2646[RESTEASY-2646]
* {issue-base-url}/RESTEASY-2782[RESTEASY-2782]
* {issue-base-url}/RESTEASY-2849[RESTEASY-2849]
* {issue-base-url}/RESTEASY-2866[RESTEASY-2866]

"Minor nit, this should just be https://issues.redhat.com/browse. We migrated away from the issue-base-url for ease of copy/paste when reviewing."

Done

**Comment by ronsigal** [comment]
* resteasy.match.cache.enabled:                       [RESTEASY-2646]
 * resteasy.match.cache.size:                          [RESTEASY-2646]
 * resteasy.original.webapplicationexception.behavior: [RESTEASY-2782]
 * resteasy.patch.filter.disabled:                     [RESTEASY-2280]
 * resteasy.patch.filter.legacy:                       [RESTEASY-2849]
 * resteasy.proxy.implement.all.interfaces:            [RESTEASY-2866]

"Should we drop the resteasy prefix from the model attribute names? I know most of them have that prefix now, but it's not strictly required and saves some typing for administators."

I made a comment on https://github.com/wildfly/wildfly/pull/17742: "What if we add a shortened version of **every** parameter, all at one time, in a new feature request. Then the old names work and each has a shortened version as well."

**Comment by ronsigal** [comment]
The wildfly/jaxrs module should be extended to expose these new parameters.

"s/wildfly/WildFly for consistency with other references."

In places where I wrote "wildfly/jaxrs", I'm referring to the code at https://github.com/wildfly/wildfly/tree/main/jaxrs. WDYT?

**Comment by ronsigal** [comment]
* resteasy.original.webapplicationexception.behavior:

   testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionMicroProfileProxyTest.java

"Should these be links? I'm not convinced they should be, but it seems like we could easily enough make them links to the source"

I updated them to be links. I would add links to the WildFly tests, but the new ones haven't been pulled in yet. Can I update this document after https://github.com/wildfly/wildfly/pull/17742 is merged?

**Comment by ronsigal** [comment]
"Please add the jekyll front matter (the categories stuff)."

Done

**Comment by ronsigal** [comment]
* {issue-base-url}/EAP7-1655[EAP7-1655]

"Nit: this is a related issue; this does not directly address EAP7-1655."

I moved it to Related Issues.

**Comment by ronsigal** [comment]
"Please add the Stability section."

In an email, @jamezp said, "I don't think we need to worry about the experimental stuff at this point.", so I set it to "default", but I can change that.

**Comment by jamezp** [comment]
Closing this as I'll be creating a new one.

**Pull request closed without merging**
