### PR TITLE
Proposal for WFCORE-5009, Enhance JBoss CLI generic 'command' with su…

### PR DESCRIPTION
**Pull request by jfdenise**
…pport for existing resource

### CODE REVIEW

**Comment by tommaso-borgato** [comment]
@jfdenise I read that it's not possible to add a command like the following at present: `command add --node-type=/core-service=management/access --command-name=access` but I wasn't able to figure out how to leverage this new attribute `--node-child` to overcome this limitation; could you please add such an example?

**Comment by jfdenise** [comment]
@tommaso-borgato , with this new option you can add a command for an existing resource only. So the path must contain type=<instanceName> otherwise the resource instance is not identified.
For example: command add --node-child=/core-service=management/access=authorization --command-name=authorization

I am also adding the WIP branch that contains new tests and help doc: https://github.com/wildfly/wildfly-core/compare/master...jfdenise:generic-command-node-child

**Comment by tommaso-borgato** [comment]
@jfdenise LGTM, I set the AD "approved" flag on https://issues.redhat.com/browse/EAP7-1501 but I don't have the permissions to merge this PR

**Comment by jfdenise** [comment]
@tommaso-borgato , the proposal will get merged at some point.

**Pull request merged**
